//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExamApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int BillDetailsID { get; set; }
        public int BillID { get; set; }
        public int ProductId { get; set; }
        public int BillQuatity { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
    }
}
